version: '3'

services:
  bd1:
    hostname: bd1
    image: kafeisystems/bd1
    build: .
    restart: on-failure
    ports:
      - "80"
    volumes:
      - ./code:/var/www/html
      - ./settings/settings.php:/var/www/html/settings.php
      - ./settings:/var/www/html/sites/default
      - ./files:/var/www/html/files
      - ./files:/var/www/html/sites/default/files
    depends_on:
      - db
  db:
    hostname: db
    image: mysql:5
    restart: on-failure
    ports:
      - "3306"
    command: --max_allowed_packet=32505856
    stdin_open: true
    tty: true
    environment:
      - MYSQL_DATABASE=bd1
      - MYSQL_USER=bd1
      - MYSQL_PASSWORD=bd1
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./exports:/var/lib/mysql-files
